Send actions with handshake packet, remove client mod filters
QuiltServerTools/Ledger pull request #112
Opened 2021-11-09 19:26 UTC by yitzy299

2021-11-09 20:06 UTC, vacla submitted a review, later dismissed

2021-11-13 21:26 UTC, PotatoPresident requested changes

2021-11-13 21:26 UTC, PotatoPresident commented on src/main/kotlin/com/github/quiltservertools/ledger/config/NetworkingSpec.kt
> -    val allowByDefault by required<Boolean>()
Confirm this doesn't cause errors with old configs. Also I don't think you removed them from the actual default config

2021-11-14 17:22 UTC, PotatoPresident approved these changes

2021-11-14 17:36 UTC, merged