Expand logging capabilities
QuiltServerTools/Ledger pull request #197
Opened 2023-03-09 16:50 UTC by nikijaz

This PR expands logging capabilities and fixes some bugs. This also includes changes from #119 by Altirix.

**Added logging of:**
- Dyeing and shearing sheep (Including evoker as a source)
- Breaking a bed due to interaction
- Breaking a cactus, sugarcane, and chorus because of gravity
- Shooting a chorus flower
- Destroying a wither or (snow) golem statue
- Modifying a state of comparator or repeater
- Opening or closing a door, trapdoor, fence gate (Including redstone as a source)
- Breaking a lily pad with a boat
- Changing or destroying an armor stand
- Changing or destroying a frame
- Painting a dog or cat collar
- Breaking blocks by an ender dragon
- Dropping and picking up items
- Setting fire with lightning
- Making snow with a snow golem
- Turning a villager into a witch because of lightning

2023-03-09 22:08 UTC, DrexHD requested changes
Wow! This is a pretty big PR with a lot of changes.
I have added some small reviews to some parts of the code. I am putting some other things I would like to mention that didn't fit a specific piece of code here:

- `@ModifyArgs` is used in a couple of Mixins to get easy access to arguments. According to the Java Doc of ModifyArgs, it is pretty inefficient and this isn't really its intended use-case. I suggest using LocalCapture instead.
- This PR added a couple of mixins for plants breaking. Their source is `Gravity`, I think it would be great to add a separate source type for this, to allow better user blacklists (This would apply to CactusBlockMixin, SugarCaneBlockMixin, BambooBlockMixin, ChorusPlantBlock, and PointedDripstoneBlockMixin)
- This is probably a design choice, but since entity modify actions store entity positions, the entity is moved back to the action pos when rolling back (even if the position doesn't really matter, like dyeing).
- Item frame logging didn't work properly when I tried rolling back `@equip` actions
- When placing carved pumpkins (and probably wither skeleton skull) it first logs the block being broken by snowman spawning and then tries to log the placed block, but since it's no longer there it logs placing air (so the order is incorrect and the placed block is wrong)
- `ItemDropActionType` and `ItemPickUpActionType` should implement rollback / restore

Thanks for the PR!

2023-03-15 17:28 UTC, suerion commented
I think on this Pull Request, there should also be the #202 projectile shoot event

2023-03-31 14:08 UTC, nikijaz commented on src/main/kotlin/com/github/quiltservertools/ledger/database/Tables.kt
> +        val entityState = text("entity_state").nullable()
Yeah, good idea, did it. But now there is a naming inconsistency, so maybe we should consider renaming it to `oldState` and `newState` in the future

2023-04-11 21:36 UTC, DrexHD requested changes
The new changes look pretty good 👍. I have left some more change request on some minor issues. 

I have also noticed an issue, when rolling back an armorstand that was first equipped and then killed. (The killing gets rolled back, but equipping doesn't, if both are rolled back in one operation)! I don't know what might cause this atm.
I think you *should* also remove the code duplication in `ItemDropActionType` and `ItemPickUpActionType` `rollback`/`restore`.

*Sorry for the slow responses, I was/am kind of busy currently*

2023-04-30 01:14 UTC, abitcher commented
This isn't compatible with Goodall. There's an item called the Animal Crate that can capture animals, that isnt logged by this.
![Uploading image_2023-04-30_111441409.png…]()

2023-04-30 01:14 UTC, abitcher commented
This isn't compatible with Goodall. There's an item called the Animal Crate that can capture animals, that isnt logged by this.
![image_2023-04-30_111441409](https://user-images.githubusercontent.com/106140253/235330887-71dac0e8-15d7-4894-8bd9-338d0ef7ab5e.png)

2023-07-03 23:26 UTC, DrexHD submitted a review, later dismissed
Looks good to me!

2023-08-23 19:52 UTC, Dev0Louis commented
Any news on this?

2023-10-21 10:38 UTC, Rozbiynk commented
any updates?

2023-10-21 14:00 UTC, DrexHD submitted a review, later dismissed

2023-11-26 14:52 UTC, DillonB07 commented
Would it be possible for this to be merged soon? Had an issue on my server that this would've solved but instead I had to go and move region files from an old backup as ledger hadn't logged the destruction.

2023-12-12 11:38 UTC, Rozbiynk commented
i hope it will have 1.20.1 version

2023-12-28 05:02 UTC, TheDeathlyCow commented
I've done some testing and can confirm that this branch works on 1.20.2 by just merging in [1.2.9](https://github.com/QuiltServerTools/Ledger/tree/1.2.9). 

There are, however, a couple of issues when merging in [update to 1.20.4](https://github.com/QuiltServerTools/Ledger/commit/a85a1e2d988d706f7dc625977f002ced969638a1). 

First, The `setBlockState` target for the injection [`TrapdoorBlockMixin#logTrapdoorInteraction`](https://github.com/nikijaz/Ledger/blob/more-logging/src/main/java/com/github/quiltservertools/ledger/mixin/blocks/TrapdoorBlockMixin.java) no longer exists. I think this can be fixed by changing the target to the `flip` call instead, as that seems to be the replacement. 

Second, the [`BedBlockMixin`](https://github.com/nikijaz/Ledger/blob/more-logging/src/main/java/com/github/quiltservertools/ledger/mixin/blocks/BedBlockMixin.java) has some invalid descriptors. It seems that `onBreak` now returns a `BlockState` so just changing the callback info param to `CallbackInfoReturnable<BlockState>` fixes that. 

Those are the only 2 errors I encountered with 1.20.4. Fixing them locally gets the mod running, and everything still seems to work.

2024-02-11 05:13 UTC, PotatoPresident requested changes

2024-02-11 05:49 UTC, PotatoPresident commented
I can't help but feel that `sources` is being misused, but I don't really have a better alternative other than making a ton of different action types.

2024-02-11 07:09 UTC, PotatoPresident approved these changes

2024-02-11 07:09 UTC, merged