Update to 1.21.2/3
QuiltServerTools/Ledger pull request #293
Opened 2024-10-29 13:07 UTC by DrexHD

2024-10-29 14:01 UTC, viperxx commented
Just built and installed on my test server, working great so far, thank you for updating!

2024-11-10 08:44 UTC, P5ina commented
Is it ready to use in production?

2024-11-10 11:26 UTC, DrexHD commented
Should be usable. Waiting for @PotatoPresident to review.

2024-11-13 01:38 UTC, PotatoPresident requested changes

2024-11-13 01:38 UTC, PotatoPresident commented on src/main/kotlin/com/github/quiltservertools/ledger/actions/ItemDropActionType.kt
> +        return if (item is BlockItem) {
This breaks with items like wheat seeds, which are block items but only have item translations

2024-11-13 19:53 UTC, PotatoPresident submitted a review, later dismissed

2024-11-13 19:58 UTC, PotatoPresident approved these changes

2024-11-13 20:13 UTC, merged