Add extension API
QuiltServerTools/Ledger pull request #78
Opened 2021-08-31 20:01 UTC by yitzy299

This PR adds an extension API for new database types and for subcommands installable via extension.

More information can be found on the docs, with a rendered view found [here](https://github.com/QuiltServerTools/Ledger/blob/api/docs/extensions/extension_development.md)

2021-09-01 17:09 UTC, BasiqueEvangelist commented
Why is a subcommand api needed? Can't extensions just register their commands under `/ledger`?

2021-09-02 08:16 UTC, yitzy299 commented
> Why is a subcommand api needed? Can't extensions just register their commands under `/ledger`?

Permissions are already handled by /ledger. It’s a small thing but might avoid issues

2021-09-03 21:46 UTC, PotatoPresident requested changes

2021-09-03 21:46 UTC, PotatoPresident commented on src/main/kotlin/com/github/quiltservertools/ledger/api/ExtensionManager.kt
> +    var commands = mutableListOf<CommandExtension>()
```suggestion
    val commands = mutableListOf<CommandExtension>()
```

2021-09-03 23:24 UTC, PotatoPresident approved these changes

2021-09-04 08:08 UTC, merged